### ISSUE TITLE
.NET 5.0 support

### ISSUE THREAD

**Issue by detunized** [isen-ng/homebrew-dotnet-sdk-versions#100]
I think `dotnet-sdk3-1-400` no longer conflicts with the official cask after it got upgraded to 5.0. Would it be possible to update the tap? Thanks.

**Comment by isen-ng** [comment]
Yes I can update `dotnet-sdk3-1-400` so that I no longer conflicts.

PRs welcome for dotnet-core 5.0!

**Comment by detunized** [comment]
Cool! Possibly for as long as 5.0 is the main version, no special cask is
needed. It could simply be installed via brew.

**Comment by isen-ng** [comment]
Closed by https://github.com/isen-ng/homebrew-dotnet-sdk-versions/pull/101
