### ISSUE TITLE
Upgrading main version removes tap versions

### ISSUE THREAD

**Issue by apeeters** [isen-ng/homebrew-dotnet-sdk-versions#113]
Hi,
After upgrading the main version to 5.0, the tap version 2.1.800 I had installed was removed from the `/usr/local/share/dotnet/sdk` directory. A reinstall of the tap version was necessary.

Can this behaviour be avoided, or otherwise documented?

**Comment by apeeters** [comment]
This warning should probably be extended to include upgrades?

"Uninstalling the offical dotnet-sdk casks will remove the shared runtime dependencies"

**Comment by isen-ng** [comment]
Sorry for the late response!

You're right. If the default behaviour of .NET5.0 is to remove other dotnet versions, then I'll need to add more caveats.
