### ISSUE TITLE
Support for .net 5

### ISSUE THREAD

**Issue by bviale** [isen-ng/homebrew-dotnet-sdk-versions#114]
Hey,

Thanks for your tap, looks like a great solution to handle multiple versions of .net on macos. I'm don't know much about Homebrew but I think you'll need to add a new cask to support .net 5 right ? Will you plan to add it ?
Currently I have 3.1.100 installed and I see no way to add 5.0.100 without removing 3.1.100.

**Comment by isen-ng** [comment]
Hi @bviale 

Thank you for your kind words. I have things going on right now that I am unable to add a cask for .net5 right now.
However, PRs are welcome!

> Currently I have 3.1.100 installed and I see no way to add 5.0.100 without removing 3.1.100.

For this, it does seem like this is the default behaviour in .NET5.0. See https://github.com/isen-ng/homebrew-dotnet-sdk-versions/issues/113

To have both versions installed, you'll need to install/upgrade .net5.0 and then re-install 3.1.100 again.
