### ISSUE TITLE
Add support for installing preview versions

### ISSUE THREAD

**Issue by brokenthorn** [isen-ng/homebrew-dotnet-sdk-versions#149]
It would be nice if you supported installing preview versions of .NET as well. For example, in order to have both .NET 5 and .NET 6 preview 4 (as of late) installed.

**Comment by isen-ng** [comment]
Unfortunately, maintaining the updated-ness of the preview version is going to be tedious. Too tedious for any manual maintaining. When that happens, the cask becomes un-updated, and soon becomes a useless task.

The regular casks are automatically updated according to a release file that the .NET core team maintains, and remains up to date (automatically) by reading release file periodically.

In this case, all the existing (non-preview) casks do not "conflict" with the official preview cask, so you can install .NET 5 from this cask, and .NET 6 preview from the official cask.

**Comment by isen-ng** [comment]
Closing for now
