### ISSUE TITLE
Dotnet 7 preview support

### ISSUE THREAD

**Issue by hughesjs** [isen-ng/homebrew-dotnet-sdk-versions#224]
Can we get support for the dotnet 7 preview

**Comment by isen-ng** [comment]
@hughesjs finally came around to supporting preview versions.

I no longer have access to a mac that can thoroughly test this release. I would appreciate it if I could get feedback as to whether this release is working or not.

**Comment by hughesjs** [comment]
Nice one my dude, seems to work well, thank you!
