### ISSUE TITLE
Feature request. Tap for Oracle JDK

### ISSUE THREAD

**Issue by TMammadov** [isen-ng/homebrew-dotnet-sdk-versions#236]
Hi Isen,

Could you please create another tap with the possibility of installing multiple Oracle JDKs?

Best,
Tural

**Comment by isen-ng** [comment]
I haven't looked at JDKs for a long time (sorry for my ignorance), but isn't this already supported by cask-versions?

https://gist.github.com/gwpantazes/50810d5635fc2e053ad117b39b597a14#this-guide-favors-openjdk

**Comment by isen-ng** [comment]
hmm, do you know if there is a repository/file that tracks Oracle JDK releases?
Something similar to (but doesn't need to be the same) https://github.com/dotnet/core/tree/main/release-notes

I'm asking to see if I could automate the maintenance of the new cask

**Comment by isen-ng** [comment]
I've been looking at the Oracle archives and downloads pages and I can't seem to find an easy way to automate the maintenance.

https://www.oracle.com/java/technologies/downloads/
https://www.oracle.com/java/technologies/downloads/archive/

If the maintenance cannot be automated, the cask will go out of date very quickly and it will be a useless cask

**Comment by isen-ng** [comment]
@TMammadov sdkman already has this:

https://sdkman.io/jdks#oracle

**Comment by isen-ng** [comment]
closing for now
