### ISSUE TITLE
Run updates more frequently

### ISSUE THREAD

**Issue by withinfocus** [isen-ng/homebrew-dotnet-sdk-versions#275]
Per https://github.com/isen-ng/homebrew-dotnet-sdk-versions/blob/master/.github/workflows/auto-updater.yml#L6 updates happen once a week, but Action runner minutes are pretty gracious these days and it would be nice to have this run as frequently as nightly. Can the schedule get a bump?

**Comment by mxplusb** [comment]
Also bump ;)

**Comment by isen-ng** [comment]
Seems fair. Let me set it up
