### ISSUE TITLE
add NET8 as rc1

### ISSUE THREAD

**Issue by jkone27** [isen-ng/homebrew-dotnet-sdk-versions#283]
could you add net8 rc1 ? or just keep as net8 and fetch latest when rc2 or LTS available?

**Comment by isen-ng** [comment]
Hello, I'm a little busy with personal life right now ... but PRs are welcome

**Comment by Xerxes-2** [comment]
#285 Hi, I created a pull request to resolve this

**Comment by isen-ng** [comment]
Fixed in https://github.com/isen-ng/homebrew-dotnet-sdk-versions/pull/285
