### ISSUE TITLE
[Bug]: Installing NET3.0 on M2 Mac

### ISSUE THREAD

**Issue by mahyarmirrashed** [isen-ng/homebrew-dotnet-sdk-versions#298]
Is there something equivalent to `dotnetx64` for running the even older versions of .NET?

**Comment by isen-ng** [comment]
Older versions of .NET like 3.0 does not have an ARM version and are x86 by default. That's why there wasn't a need for `dotnetx64` for them.

Simply run `dotnet` to get the x86 version

**Comment by mahyarmirrashed** [comment]
Oh I understand. Does that necessarily mean that you cannot run those older versions on M2 ARM-based chip Macs without some sort of translating software like Rosetta?

**Comment by isen-ng** [comment]
Yes, I think you're right. Rosetta should automatically kick in for x86 applications, shouldn't it?

**Comment by mahyarmirrashed** [comment]
I tried it out, but, my results were being kind of wild. I've moved away from the project that I was working on that was related to this ticket, so I guess that we can probably close it for now until the next person asks about it.
