### ISSUE TITLE
Feature request: metapackages

### ISSUE THREAD

**Issue by fluffynuts** [isen-ng/homebrew-dotnet-sdk-versions#304]
Good day

Thanks so much for this repo, which makes having side-by-side installations of different versions of the dotnet sdk possible via the homebrew package manager.

I have one request though - please could you add metapackages, eg `dotnet-sdk7` and `dotnet-sdk8` which would install the latest of those runtimes? I would have liked to have raised a PR to contribute, but I must be missing some brew-fu, because the following didnt' work:

1. symlink dotnet-sdkN-x-x.rb to dotnet-sdkN.rb (brew complains that the package name and file name don't match)
2. creating a new .rb file with the following contents doesn't work either (so I'm not sure what to do to make a metapackage as yet - if you don't know either, I'll dig in again, but I hardly ever use a mac, so it will take me a while 😅 

```ruby
cask "dotnet-sdk8" do
  arch arm: "arm64", intel: "x64"
  depends_on macos: ">= catalina", cask: "dotnet-sdk8-0-100"
end
```
(the above leaves brew complaining about where to download things from, so I'm obviously doing something wrong.

The reason I'm asking is so that a user can do, eg:
```bash
brew install dotnet-sdk7
brew install dotnet-sdk-8
# and some time later, when a new version of dotnet 8 is released
brew upgrade # should upgrade dotnet 8 without the user having to figure out what the latest is, or, indeed, that there was even an update
```

**Comment by isen-ng** [comment]
Hello!

Thank you for your kind words about this cask.

While the idea of meta packages sound like a good idea, the devil is in the automated update script.

I have a script that automatically detects new dotnet releases and updates the existing casks automatically. There is significant effort to extend the update script to support meta packages. It would be useless to have a meta package that is not consistently updated.

I'll leave this here and monitor the amount of interest for this feature against the effort required.

Folks who are interested in this feature, please give a thumbs up to this issue.

**Comment by fluffynuts** [comment]
Hi @isen-ng 

Am I correct in saying that the updater script is `auto_updater.py`? If so, and if you can take the time to teach me how a meta package should look (ie, make just one, paste it in here), I'll look into the automation part, because I agree - a meta package which isn't up to date would be terrible! 

And I both would really like this feature for myself and so I can recommend this cask to all the mac people at my work, who will currently be using the default method and are likely to run into issues if they update any time soon because the current latest is v8, but none of our projects have been updated to that version. And when I start on it, there will still be time when they'd need to be able to build net7.0 _and_ net8.0 targets). Some of those users are not "system hackers", so I'm looking for the simplest instructions to give them to make the transition from net7.0 to net8.0 as painless as possible.

Your repo provides 90% of the above, because I'd have to teach people about installing the latest version of each major release (and cleaning out old versions - we always use the latest patch on a release) and rely on them to understand and remember. I'd love to help to resolve that.

**Comment by isen-ng** [comment]
Here is a sample `dotnet-sdk7` cask file.
It might have some styling issues we can fix later but it should generally look like this.

Important parts to update during auto-update:

1. `version`: this always comes in a pair
    - `7.0.306` this is the SDK version
    - `7.0.9` this is the runtime version
2. `sha256_x64` and `sha256_arm64`
    - these are calculated based on the installation `pkg` file
3. `url_x64` and `url_arm64`
    - the urls to actually download the `pkg` files
    - although unnecessary, these urls MUST contain some variable replacement like `#{version.csv.first}` otherwise homebrew will complain
4. `conflicts_with`: this is something I haven't thought through thoroughly yet but 
    - At the very least, this cask should conflict with the latest minor version of the same major version
        - I think... or should we simply assume users will be smart enough to resolve this by themselves?
        - It's a new auto-maintenance point to write
    - Should this conflict with EVERY minor version in the same major version? 
        - this is a question best answered after using and gathering feedback about this cask
    - Should this conflict with the official cask if the major version is the same as the official cask?
        - I think we don't need it
        - If a user needs a meta-package of the official cask, they can simply install the official cask
        - It's a maintenance overhead to track which major version is the official cask and move our conflicts with their release

```ruby
cask "dotnet-sdk7" do
  arch arm: "arm64", intel: "x64"

  version "7.0.306,7.0.9"

  sha256_x64 = "129c927b3e0446bec06583f659d2f6681e6551b2ef7c7f258bc0b3ca97b7c214"
  sha256_arm64 = "50a412b0e7e4da20d846de5afe17ea0874697db044b049ab2021eef8824e6b34"
  url_x64 = "https://download.visualstudio.microsoft.com/download/pr/534a66a3-31a4-4cf7-9866-319414f5876d/f6e644cc2bdcab7801efef1c533e8400/dotnet-sdk-#{version.csv.first}-osx-x64.pkg"
  url_arm64 = "https://download.visualstudio.microsoft.com/download/pr/4cfe3db4-4922-404d-b2de-db478a9a6c4a/5ec100c639e38cac64a61a02c9ab4df7/dotnet-sdk-#{version.csv.first}-osx-arm64.pkg"

  on_arm do
    sha256 sha256_arm64

    url url_arm64
  end
  on_intel do
    sha256 sha256_x64

    url url_x64
  end

  name ".NET Core SDK #{version.csv.first}"
  desc "This cask follows releases from https://github.com/dotnet/core/tree/master"
  homepage "https://www.microsoft.com/net/core#macos"

  livecheck do
    skip "See https://github.com/isen-ng/homebrew-dotnet-sdk-versions/blob/master/CONTRIBUTING.md#automatic-updates"
  end

  conflicts_with cask: [
    "homebrew/isen-ng/dotnet-sdk7-0-300"
  ]

  depends_on macos: ">= :mojave"

  pkg "dotnet-sdk-#{version.csv.first}-osx-#{arch}.pkg"

  uninstall pkgutil: "com.microsoft.dotnet.dev.#{version.csv.first}.component.osx.#{arch}"

  zap trash:   ["~/.dotnet", "~/.nuget", "/etc/paths.d/dotnet", "/etc/paths.d/dotnet-cli-tools"],
      pkgutil: [
        "com.microsoft.dotnet.hostfxr.#{version.csv.second}.component.osx.#{arch}",
        "com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.#{version.csv.second}.component.osx.#{arch}",
        "com.microsoft.dotnet.pack.apphost.#{version.csv.second}.component.osx.#{arch}",
        "com.microsoft.dotnet.sharedhost.component.osx.#{arch}",
      ]

  caveats "Uninstalling the offical dotnet-sdk casks will remove the shared runtime dependencies, " \
          "so you'll need to reinstall the particular version cask you want from this tap again " \
          "for the `dotnet` command to work again."
end
```

**Comment by isen-ng** [comment]
I haven't got access to my personal mac yet but I think this should work:

filename `dotnet-sdk7.rb`

```ruby
cask "dotnet-sdk7" do
  depends_on macos: ">= :mojave", cask: "homebrew/isen-ng/dotnet-sdk7-0-300"
end
```

**Comment by isen-ng** [comment]
It seems to me that the update automation for these meta-casks might be completely different from the existing update script, I think it will be better to create a separate python file and github workflow to automatically update these meta-casks

**Comment by fluffynuts** [comment]
I started looking into this, have tests started out and all that, and then I thought, lemme just check that the example above does what we need to, so I create a file `/usr/local/Homebrew/Library/Taps/isen-ng/homebrew-dotnet-sdk-versions/Casks/dotnet-sdk78.rb` with the contents
```ruby
cask "dotnet-sdk7" do
    depends_on macos: ">= :mojave", cask: "homebrew/isen-ng/dotnet-sdk7-0-400"
end
```
(which should only differ from your example above by the selected version - I chose the highest, of course)

Running `brew install dotnet-sdk7`, I get the same error I got when I was futzing about before raising this issue:

```
Error: attempted to use a Downloadable without a URL!
```

So I'll have to go figure out what homebrew _really_ wants for a meta package, or perhaps there's a kludge to work around this? What are your thoughts?

**Comment by isen-ng** [comment]
I know why now.
See https://docs.brew.sh/Cask-Cookbook#required-stanzas

A cask cannot be something just to install other casks. It must have an URL etc.

Thus, we will have to build a full cask for this to work, instead of a simple redirection

**Comment by isen-ng** [comment]
There might be a hack around this: https://github.com/Ensembl/homebrew-cask

**Comment by fluffynuts** [comment]
well, that really makes the meta package tool easy to do (:

it no longer needs to understand Ruby, it can just find the highest one and copy it - I'll have something available the moment I'm back in code-land (read: probably monday-ish)

**Comment by fluffynuts** [comment]
I was thinking about this more over the weekend, and perhaps a pure copy-paste isn't the best idea because it essentially makes two packages which target the same result - so they should conflict with each other.

How about this then: a README hosted in this repo is the "downloadable artifact" which we "install" somewhere, and all it says is that the meta package pulls in the highest version - and of course, it depends on the highest version. It's a little more complex (back to producing ruby code & i have to learn proper package definition!) but I think it's the "more correct" approach - if the package manager demands that a package install something, that's (imo) an oversight (because it makes meta packages harder to make), but we can work around that, I think (:

**Comment by fluffynuts** [comment]
btw, I've made some progress on this, using the above idea for the method (ie, including a new META.md that explains why it's there, but it's the only downloadable artifact, and it pulls in the "proper" version of the package). I've successfully tested a handmade formula as described - and it worked fine - and I'm probably about 80% through having a script to generate the meta formulae (: Hopefully should be able to complete in the next window I have to work on this, next friday afternoon (:

**Comment by fluffynuts** [comment]
I've raised a PR: #310 - the results work for me, but I could have missed something - please review when you have a chance (:

**Comment by memark** [comment]
This is fantastic! Good work with that PR @fluffynuts!

(Btw, time to close this issue, no?)

**Comment by isen-ng** [comment]
Hmm, I'm still missing some README updates: https://github.com/isen-ng/homebrew-dotnet-sdk-versions/pull/310#issuecomment-2056969546

I think I'll spend some time to work on them this weekend and close this

**Comment by isen-ng** [comment]
fixed in https://github.com/isen-ng/homebrew-dotnet-sdk-versions/pull/361
