### ISSUE TITLE
version 2.2.8?

### ISSUE THREAD

**Issue by kuwaitbinary** [isen-ng/homebrew-dotnet-sdk-versions#38]
Hello thank you for the Tap but is it possible to add dotnet version 2.2.8, please?

[https://github.com/dotnet/core/releases/tag/v2.2.8](url)

**Comment by isen-ng** [comment]
By 2.2.8, I think you meant dotnet runtime 2.2.8. There is no such thing as a dotnet sdk 2.2.8.

For dotnet sdks that support runtime 2.2.8, you can install either 2.2.207 or 2.2.110, of which both comes with runtime 2.2.8

```
# installs 2.2.207 which comes with runtime 2.2.8
brew cask install dotnet-sdk-2.2.200

# or, installs 2.2.110 which comes with runtime 2.2.8
brew cask install dotnet-sdk-2.2.100
```

PS, there is no 2.2.400 sdk release with 2.2.8 runtime. Latest is 2.2.402 with 2.2.7.

**Comment by isen-ng** [comment]
Closing because this is already implicitly supported.
